### ISSUE TITLE
Error when using xargs

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/ebi#87]
I tried using `xargs` and got the following error.

```
$ http 'https://tako.in.ft.com/tako/repositories?topic=app' "Authorization:Bearer $(heroku config:get --app ft-next-tako BEARER_TOKEN)" | jq -r '.repositories[] | "\(.owner)/\(.name)"' | xargs npx ebi --token $VAULT_AUTH_GITHUB_TOKEN contents app.json
choose either to pipe through a repo list OR pass it as args
```

I know some command line tools have an option like `--ignore-std-in` to deal with this issue.

I also think we can provide the user with a better error message, example usage would be awesome.

**Comment by taktran** [comment]
Thinking about it a bit, I don't think we get much by having `ebi` error when we have input from both stdin and args. We should just concat the two lists and let it happen.

Any objections?

**Comment by sjparkinson** [comment]
No objections at all 🚀

**Comment by taktran** [comment]
For reference, these are all the results of all the different possibilities of stdin/args at the end/xargs:

**NOTE**: When using [arguments at the end](https://github.com/yargs/yargs/blob/master/docs/advanced.md#variadic-positional-arguments), you need to have an empty search (ie, `''`), otherwise ebi thinks you are searching for 'Financial-Times/next-static' for no repos, and hence returns nothing

### stdin

    $ echo 'Financial-Times/next-static' | ./bin/ebi.js package ''
    Financial-Times/next-static

### args

    $ ./bin/ebi.js package '' Financial-Times/next-static
    Financial-Times/next-static

### stdin + args

    $ echo 'Financial-Times/next-static' | ./bin/ebi.js package '' 'Financial-Times/next-search-page'
    ebi.js package [search] [repo..]
    ...
    Error: choose either to pipe through a repo list OR pass it as args
    ...

### stdin + xargs

    $ echo 'Financial-Times/next-static' | xargs ./bin/ebi.js package ''
    ebi.js package [search] [repo..]
    ...
    Error: choose either to pipe through a repo list OR pass it as args
    ...

### stdin + xargs + args

    $ echo 'Financial-Times/next-static' | xargs ./bin/ebi.js package '' 'Financial-Times/next-search-page'
    ebi.js package [search] [repo..]
    ...
    Error: choose either to pipe through a repo list OR pass it as args
    ...
